name: Depolyment

on:
  push:
    branches: [ master ]

jobs:
    depoly:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: "12"

            - name: Install Dependencies
              run: npm install

#            - name: Check
#              run: npm run check

#            - name: Test
#              run: npm run test

#            - name: Generate AdapterHub Data
#              run: npm run generate:adapterhub

            - name: Build
              run: npm run build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: ./dist